[package]
name = "gomoku-api"
version = "1.0.0"
authors = ["kyazdani42 <yazdani.kiyan@protonmail.com>, vguillem <vguillem@student.42.fr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
